# @use ./rts/helpers.rts

### List items
# @name List items
GET {{base.url}}/api/items

### List articles only
# @name List articles only
GET {{base.url}}/api/items?kind=article

### List bookmarks only
# @name List bookmarks only
GET {{base.url}}/api/items?kind=bookmark

### List notes only
# @name List notes only
GET {{base.url}}/api/items?kind=note

### List tasks only
# @name List tasks only
GET {{base.url}}/api/items?kind=task

### List videos only
# @name List videos only
GET {{base.url}}/api/items?kind=video

### List new items
# @name List new items
GET {{base.url}}/api/items?status=new

### List done items
# @name List done items
GET {{base.url}}/api/items?status=done

### List 2 items with 1 offset
# @name List items with offset and limit
GET {{base.url}}/api/items?limit=2&offset=1


### New article item fetching title
# @name New Article item
POST {{base.url}}/api/items
Content-Type: application/json

{
  "url": "https://blog.annimon.com/wezterm-projects/",
  "kind": "article",
  "tags": "wezterm, terminal",
  "created_at": "2026-06-25T10:00:00+03:00"
}


### New bookmark item
# @name New Bookmark item
POST {{base.url}}/api/items
Content-Type: application/json

{
  "url": "https://blog.annimon.com/wezterm-projects/",
  "kind": "bookmark",
  "tags": "wezterm, terminal",
  "created_at": "2026-06-25T10:00:00+03:00"
}


### New note item
# @name New Note item
POST {{base.url}}/api/items
Content-Type: application/json

{
  "kind": "note",
  "title": "New Note",
  "content": "Note content here",
  "created_at": "2026-06-25T10:00:00+03:00"
}


### New task item
# @name New Task item
POST {{base.url}}/api/items
Content-Type: application/json

{
  "kind": "task",
  "title": "ToDo",
  "content": "- Item 1\n- Item 2\n- Item 3",
  "created_at": "2026-06-25T10:00:00+03:00"
}
